---
dist: trusty
language: python
python: "2.7"

sudo: false

addons:
  apt:
    update: true
    packages:
      - shellcheck

script:
  # Run shellcheck on my shell functions file
  - echo "shellcheck on .shfuncs"
  - shellcheck -s bash -e SC2034 .funcs.sh
  # Search tabulation
  - echo "searching tabulations"
  - bash -c '! find . -type f -name ".*" | xargs grep -nP "\t"'
  # Search trailing whitespaces
  - echo "searching trailing whitespaces"
  - bash -c '! find . -type f -name ".*" | xargs grep -nP " $"'
