---
dist: trusty
language: python
python: "2.7"

sudo: false

addons:
  apt:
    update: true
    packages:
      - shellcheck

script:
  # Run shellcheck on my shell functions file
  - echo -en 'travis_fold:start:shellcheck\rshellcheck'
  - shellcheck --version
  - shellcheck -s bash -e SC2034 .funcs.sh
  - echo -en 'travis_fold:end:shellcheck\r'
  # Search tabulations
  - echo -en 'travis_fold:start:tabulations\rsearch tabulations'
  - bash -c '! find . -type f -name ".*" | xargs grep -nP "\t"'
  - echo -en 'travis_fold:end:tabulations\r'
  # Search trailing whitespaces
  - echo -en 'travis_fold:start:trailing_whitespaces\rsearch whitespaces'
  - bash -c '! find . -type f -name ".*" | xargs grep -nP " $"'
  - echo -en 'travis_fold:end:trailing_whitespaces\r'
