gui:
  scrollheight: 2
  theme:
    activebordercolor:
    - blue
    - bold
    inactivebordercolor:
    - white
    optionstextcolor:
    - green
reporting: "off"
keybinding:
  universal:
    appendNewline: '<tab>'  