---
name: Docker Image CI
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Shellcheck
      run: sudo apt-get install -y shellcheck

    - name: Run checks 
      run: |
        find . -name "*.sh" | xargs shellcheck -s bash -S error

    - name: Send Telegram Message using curl
      if: always()
      run: |
        [[ "${{ job.status }}" == "success" ]] && STATUS="✅" || STATUS="❎"
        REPOSITORY=$( echo ${{ github.repository }} | cut -d '/' -f 2 )
        MESSAGE="\`\`\`
        action         : Build of Docker Image
        repository     : $REPOSITORY
        commit message : ${{ github.event.head_commit.message }}
        status         : $STATUS
        \`\`\`
        See logs [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MESSAGE" \
            -d parse_mode=Markdown
...
